global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: "kafka_exporter"
    static_configs:
      - targets: ["kafka_exporter:9308"]

  - job_name: "postgres_exporter"
    static_configs:
      - targets: ["postgres_exporter:9187"]

  - job_name: "pipeline_metrics"
    static_configs:
      - targets: ["pipeline_metrics:8000"]
